name         'rfletcher-nagios'
version      '0.0.1'
license      'MIT License'
summary      'Nagios Core and NRPE'
description  'A puppet module for Nagios Core and NRPE'
project_page 'https://github.com/rfletcher/puppet-nagios'
